/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package github.chenupt.springindicator.multiplemodel.viewpager;

import android.support.v4.app.Fragment;

import java.util.ArrayList;
import java.util.List;

public class PagerModelManager {
    public static final String DATA = "data";
    private List<Fragment> fragmentList;
    private List<CharSequence> titleList;

    
    public PagerModelManager() {
        titleList = new ArrayList();
        fragmentList = new ArrayList();
    }
    
    public Fragment getItem(int position) {
        return (Fragment)fragmentList.get(position);
    }
    
    public int getFragmentCount() {
        return fragmentList.size();
    }
    
    public boolean hasTitles() {
        return (titleList.size() != 0);
    }
    
    public CharSequence getTitle(int position) {
        return (CharSequence)titleList.get(position);
    }
    
    public PagerModelManager addFragment(Fragment fragment, CharSequence title) {
        titleList.add(title);
        addFragment(fragment);
        return this;
    }
    
    public PagerModelManager addFragment(Fragment fragment) {
        fragmentList.add(fragment);
        return this;
    }
    
    public PagerModelManager addCommonFragment(Class<?> c, List<Fragment> list, List<String> titleList) {
        titleList.addAll(titleList);
        //addCommonFragment(c, list);
        addCommonFragment(list);
        return this;
    }
    
  /*  public PagerModelManager addCommonFragment(Class<?> c, List<Fragment> list) {
        fragmentList.addAll(list);
        return this;
    }*/
    
    public PagerModelManager addCommonFragment(List<Fragment> list) {
        fragmentList.addAll(list);
        return this;
    }
    
    public PagerModelManager addCommonFragment(List<Fragment> list, List<String> titleList) {
        titleList.addAll(titleList);
        addCommonFragment(list);
        return this;
    }
}
